apiVersion: v2
name: gitops-web-app
description: A GitOps demo web application with MySQL backend
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: 9.4.6
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
